# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
