# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-18 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tag',
        ),
    ]
