# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
