# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 16:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181015_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
