# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='paid',
        ),
    ]
